name: brainstaff
volumes:
  mongo:
    name: brainstaff-mongo
  mongo-config:
    name: brainstaff-mongo-config
  postgres:
    name: brainstaff-postgres
networks:
    default:
      name: brainstaff
services:
  mongo:
    image: mongo:8
    volumes:
      - mongo:/data/db
      - mongo-config:/data/configdb
    ports:
      - $MONGO_PORT:27017
    restart: unless-stopped
  postgres:
    image: postgres:17
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: brainstaff
      POSTGRES_PASSWORD: brainstaff
    restart: unless-stopped
